const styleMaps = {
    CLASSES: {
        'alert': 'alert',
        'badge': 'badge',
        'banner': 'banner',
        'brand': 'brand',
        'breadcrumb': 'breadcrumb',
        'button': 'btn',
        'btn-icon': 'btn-icon',
        'button-group': 'btn-group',
        'btn-content': 'btn-content',
        'button-toolbar': 'btn-toolbar',
        'caret': 'caret',
        'checkbox': 'checkbox',
        'checkbox-radio-label': 'checkbox-radio-label',
        'check-style': 'check-style',
        'collapse': 'collapse',
        'collapse-group': 'collapse-group',
        'column': 'col',
        'control-group': 'form-group',
        'control-label': 'control-label',
        'controls': 'controls',
        'divider': 'divider',
        'dropdown': 'dropdown',
        'dropdown-toggle': 'dropdown-toggle',
        'dropdown-menu': 'dropdown-menu',
        'dropdown-menu-right': 'dropdown-menu-right',
        'dropdown-header': 'dropdown-header',
        'form': 'form',
        'form-actions': 'form-actions',
        'form-horizontal': 'form-horizontal',
        'glyphicon': 'glyphicon',
        'checkbox-group': 'checkbox-group',
        'radio-group': 'radio-group',
        'help-block': 'help-block',
        'has-success': 'has-success',
        'has-warning': 'has-warning',
        'has-error': 'has-error',
        'inline': 'inline',
        'input': 'input',
        'input-group': 'input-group',
        'label': 'label',
        'label-field': 'label-field',
        'list-group-item': 'list-group-item',
        'loader-content': 'loader-content',
        'logo': 'logo',
        'modal': 'modal',
        'modal-body': 'modal-body',
        'modal-content': 'modal-content',
        'modal-dialog': 'modal-dialog',
        'modal-footer': 'modal-footer',
        'modal-header': 'modal-header',
        'modal-title': 'modal-title',
        'modal-icon-info': 'modal-icon-info',
        'modal-icon-warn': 'modal-icon-warning',
        'modal-icon-success': 'modal-icon-success',
        'modal-icon-error': 'modal-icon-error',
        'multiple-selection': 'multiple-selection',
        'nav': 'nav',
        'navbar': 'navbar',
        'navbar-nav': 'navbar-nav',
        'pagination': 'pagination',
        'panel': 'panel',
        'panel-body': 'panel-body',
        'panel-collapse': 'panel-collapse',
        'panel-default': 'panel-default',
        'panel-group': 'panel-group',
        'panel-heading': 'panel-heading',
        'panel-title': 'panel-title',
        'progress-bar': 'progress-bar',
        'radio': 'radio',
        'row': 'row',
        'select': 'select',
        'tab-content': 'tab-content',
        'tab-pane': 'tab-pane',
        'tabbable': 'tabbable',
        'thumbnail': 'thumbnail',
        'tm-loader': 'tm-loader',
        'tree-dropdown': 'tree-dropdown',
        'well': 'well',
        'tm': 'tm',
        'collapser': 'collapser',
        'collapser-title': 'collapser-title',
        'arrow': 'arrow',
        'arrow-icon': 'fa fa-caret-right'
    },
    STYLES: [
        'ban-circle',
        'block',
        'circle-arrow-down',
        'danger',
        'default',
        'download-alt',
        'error',
        'header',
        'important',
        'info',
        'inline',
        'inverse',
        'link',
        'list',
        'ok',
        'ok-circle',
        'pills',
        'primary',
        'search',
        'star',
        'success',
        'tabs',
        'trash',
        'user',
        'warning',
        'horizontal',
        'exclamation-sign',
        'plain',
        'blue',
        'green',
        'cyan',
        'orange',
        'red',
        'indigo',
        'yellow',
        'light-gray',
        'gray',
        'dark'
    ],
    addStyle(name) {
        styleMaps.STYLES.push(name);
    },
    SIZES: {
        'large': 'large',
        'lg': 'lg',
        'md': 'md',
        'medium': 'medium',
        'sm': 'sm',
        'small': 'small',
        'xlarge': 'xlarge',
        'xs': 'xs',
        'xsmall': 'xs',
    },
    GRID_COLUMNS: 12
};

export default styleMaps;
